### ISSUE TITLE
Buttons Analyze and Authenticate inactive despite proper setup

### ISSUE THREAD

**Issue by mmenninghaus** [rappen/PowerAppsChecker#11]
Hi,

I set the tool up  last week as suggested and everything worked as expected. Unfortunately I am now neither able to Authenticate via Connect PAC, nor to Analyze, since both buttons are inactive.

![image](https://user-images.githubusercontent.com/43880502/72259411-b0189880-3610-11ea-883a-12e6692d9149.png)

![image](https://user-images.githubusercontent.com/43880502/72259587-24533c00-3611-11ea-8402-2c6ad83c55fb.png)

The Azure App Registration is setup as suggested. 
Any idea how to solve this? For us, it seems to be the only solution to validate our code against the App Source guidelines, since the ODCA tool is inaccessible. Thank you!

Best

Mathias

**Comment by rappen** [comment]
Hi - Is the Authenticate button still disabled when you enter a proper Application ID (guid) and select Geography and Language?

**Comment by rappen** [comment]
Analyze will be enabled when a solution is selected and either a ruleset is selected or 1-n rules are checked.

**Comment by mmenninghaus** [comment]
My bad, did not select a ruleset... Sorry wasting your time and Thank you for the very fast reply!

**Comment by rappen** [comment]
Anytime! 😊
