### ISSUE TITLE
For auth allow the user to select their account

### ISSUE THREAD

**Issue by mhuguet** [rappen/PowerAppsChecker#2]
There will be cases where a user needs to login as a different user in a different tenant. It appears that the current configuration that you are using is setup with a PromptBehavior of something such as Auto where is leverages any cached tokens and can end up with an error, such as below. In my case I have an application ID that I want to use in a different tenant. I am logged in already using my primary tenant and cannot switch the user within the confines of the XrmToolBox app. Consider having it as SelectAccount on the first login and afterwards using Auto. Here is a small snippet of what is done in our PowerShell module:

promptBehavior = alreadyAuthenticatedUser ? PromptBehavior.Auto : PromptBehavior.SelectAccount;

Then pass this prompt behavior to AcquireTokenAsync().

AADSTS700016: Application with identifier 'xxxxxxxxxxx' was not found in the directory 'xxxxxxxxxxxxxxx'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

**Comment by rappen** [comment]
Currently the auth is only performed when you hit the Authenticate button in the Connect dialog (or when authenticated client is required by invoking upload/analysis) and that authenticated client is used in all consecutive actions requiring the authenticated client.
Is that not a good pattern, perhaps "consecutive authentication" should be performed in code (using `PromptBehavior.Auto` or `RefreshSession`) each time an authenticated client is required?

Please advise :)

**Comment by mhuguet** [comment]
I'm not really sure how it is implemented, but you should at least do SelectAccount in the beginning for cases, such as mine.
