### ISSUE TITLE
Include an option for selecting other languages as provided by the Power Apps checker web API

### ISSUE THREAD

**Issue by mhuguet** [rappen/PowerAppsChecker#4]
The service support all the languages that Power Apps does. The list of codes are below. You can also find them as part of the ValidationSet for the LocaleName parameter in the PowerShell cmdlets. You can put the language code in the Accept-Language header of the rule and analyze API and it will do the translations for you including the results in the SARIF. You may need to tweak your parsing of the SARIF a bit to support it. We do support multiple languages as well passed in the header. We don’t currently have ruleset names being translated.

"bg", "ca", "cs", "da", "de", "el", "en", "es", "et", "eu", "fi", "fr", "gl", "hi", "hr", "hu", "id", "it", "ja", "kk", "ko", "lt", "lv", "ms", "nb", "nl", "pl", "pt-BR", "pt-pt", "ro", "ru", "sk", "sl", "sr-Cyrl-RS", "sr-Latn-RS", "sv", "th", "tr", "uk", "vi", "zh-HANS", "zh-HANT"

**Comment by rappen** [comment]
Would it be possible to retrieve the list of languages somehow?
Or they have to be hard coded?

**Comment by mhuguet** [comment]
Hard coded for now since it rarely changes.
________________________________

**Comment by rappen** [comment]
👍

**Comment by rappen** [comment]
Love it!

![image](https://user-images.githubusercontent.com/2572253/70395510-c58e1780-19ff-11ea-89d7-345d53e3f4da.png)

**Comment by mhuguet** [comment]
Nice
________________________________
